name: Run Brakeman

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Detect ruby version
        id: ruby-version
        run: echo "::set-output name=VERSION::$(cat .ruby-version)"
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ steps.ruby-version.outputs.VERSION }}'
          bundler-cache: false
      - run: bundle install

      - name: Run brakeman with reviewdog
        uses: reviewdog/action-brakeman@v2.4.0
